export const skills = [
    "Semantic & accesible HTML",
    "Responsive web design",
    "JavaScript: ES6+",
    "React",
    "Error handling",
    "GitHub: Pull Requests & Review",
    "React hooks",
    "NPM",
    "Working with API (axios, fetch)",
    "Redux(Toolkit)",
    "Immutability",
    "Promises, Async/Await",
    "Redux-Saga",
    "Markdown",
    "Debugging",
    "React Router",
    "Scrum",
    "CSS Flexbox",
    "CSS Grid",
    "Styled-components",
    "CSS BEM convection",
    "Trello",
    "MySQL",
];

export const nextSkills = [
    "Node.js",
    "TypeScript",
    "React Cotext",
    "Vue.js",
    "React Native",
];